name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - run: npm ci
      - run: npm run test
        env:
         CI: true

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ec2-user
          remote_host: ec2-107-23-130-211.compute-1.amazonaws.com
          remote_user: ec2-user
          remote_key: "${{secrets.S01_SSH_PRIVATE_KEY}}"
